version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

jobs:
  post_install:
    - pip install poetry==1.2.0b1
    - poetry config virtualenvs.create false
    - poetry install --with dev
