name: CD

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          token: ${{secrets.ADMIN_TOKEN}}
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - uses: Gr1N/setup-poetry@v8

      - name: Install semantic release
        run: |
          pip install -U pip
          pip install python-semantic-release==7.34.6

      - name: Setup user
        uses: fregante/setup-git-user@v2

      - name: Generate version and commit / tag
        run: semantic-release publish
        env:
          GH_TOKEN: ${{secrets.ADMIN_TOKEN}}

      - name: Publish package to pypi
        run: |
          poetry config pypi-token.pypi ${{secrets.PYPI_API_TOKEN}}
          poetry build
          poetry publish
